'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class IconImages
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("YTUI.IconImages", GetType(IconImages).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property ID_AddRow() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_AddRow", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_AddRow24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_AddRow24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_AddRow32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_AddRow32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Browse() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Browse", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Browse24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Browse24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Browse32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Browse32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Cancel() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Cancel", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Cancel24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Cancel24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Cancel32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Cancel32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_ChangePwd() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_ChangePwd", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Close() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Close", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Close24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Close24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Close32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Close32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_CloseAll() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_CloseAll", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_CloseAll24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_CloseAll24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_CloseAll32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_CloseAll32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Delete() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Delete", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Delete24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Delete24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Delete32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Delete32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_DeleteRow() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_DeleteRow", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_DeleteRow24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_DeleteRow24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_DeleteRow32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_DeleteRow32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Edit() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Edit", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Edit24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Edit24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Edit32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Edit32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_EditRow() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_EditRow", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_EditRow24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_EditRow24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_EditRow32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_EditRow32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Find() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Find", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Find24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Find24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Find32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Find32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_First() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_First", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_First24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_First24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_First32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_First32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Form() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Form", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Form24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Form24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Form32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Form32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Last() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Last", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Last24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Last24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Last32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Last32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Login() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Login", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_LogOff() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_LogOff", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Main() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Main", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Main24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Main24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Main32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Main32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Menu() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Menu", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Menu32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Menu32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_New() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_New", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_New24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_New24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_New32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_New32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Next() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Next", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Next24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Next24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Next32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Next32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Open() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Open", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Previous() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Previous", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Previous24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Previous24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Previous32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Previous32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Print() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Print", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Print24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Print24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Print32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Print32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Quit() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Quit", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Quit24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Quit24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Quit32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Quit32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Refresh() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Refresh", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Refresh24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Refresh24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Refresh32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Refresh32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Save() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Save", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Save24() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Save24", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Save32() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Save32", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
    
    Friend Shared ReadOnly Property ID_Welcome() As System.Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("ID_Welcome", resourceCulture)
            Return CType(obj,System.Drawing.Icon)
        End Get
    End Property
End Class
