'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class StringTable
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("YTUI.StringTable", GetType(StringTable).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to NewProject.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap__program_title_() As String
        Get
            Return ResourceManager.GetString("ID_cap__program_title_", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to (Browse Mode).
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_BrowseMode() As String
        Get
            Return ResourceManager.GetString("ID_cap_BrowseMode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to (Edit Mode).
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_EditMode() As String
        Get
            Return ResourceManager.GetString("ID_cap_EditMode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to scrap.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_item_scrap() As String
        Get
            Return ResourceManager.GetString("ID_cap_item_scrap", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to stock.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_item_stock() As String
        Get
            Return ResourceManager.GetString("ID_cap_item_stock", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_Order() As String
        Get
            Return ResourceManager.GetString("ID_cap_Order", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PoLable.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_print_po() As String
        Get
            Return ResourceManager.GetString("ID_cap_print_po", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to WO Lable.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_print_WO() As String
        Get
            Return ResourceManager.GetString("ID_cap_print_WO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to print.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_pritn() As String
        Get
            Return ResourceManager.GetString("ID_cap_pritn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ready.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_Ready() As String
        Get
            Return ResourceManager.GetString("ID_cap_Ready", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to (Search Mode).
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_SearchMode() As String
        Get
            Return ResourceManager.GetString("ID_cap_SearchMode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to securite.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_securite() As String
        Get
            Return ResourceManager.GetString("ID_cap_securite", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to stock.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_stock() As String
        Get
            Return ResourceManager.GetString("ID_cap_stock", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SwitchBoard.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_Switchboard() As String
        Get
            Return ResourceManager.GetString("ID_cap_Switchboard", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to system management.
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_system() As String
        Get
            Return ResourceManager.GetString("ID_cap_system", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Welcome To use %1....
    '''</summary>
    Friend Shared ReadOnly Property ID_cap_Welcome() As String
        Get
            Return ResourceManager.GetString("ID_cap_Welcome", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Commands.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_Command() As String
        Get
            Return ResourceManager.GetString("ID_menu_Command", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;File.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_File() As String
        Get
            Return ResourceManager.GetString("ID_menu_File", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change Pass&amp;word.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileChangePwd() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileChangePwd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Close.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileClose() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileClose", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Close &amp;All.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileCloseAll() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileCloseAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to E&amp;xit.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileExit() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileExit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Login.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileLogin() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileLogin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;LogOff.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileLogOff() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileLogOff", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;New.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileNew() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Open.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_FileOpen() As String
        Get
            Return ResourceManager.GetString("ID_menu_FileOpen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Help.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_Help() As String
        Get
            Return ResourceManager.GetString("ID_menu_Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;About .
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_HelpAbout() As String
        Get
            Return ResourceManager.GetString("ID_menu_HelpAbout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Contents.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_HelpContents() As String
        Get
            Return ResourceManager.GetString("ID_menu_HelpContents", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Search For Help On....
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_HelpSearchForHelpOn() As String
        Get
            Return ResourceManager.GetString("ID_menu_HelpSearchForHelpOn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to logs.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_logs() As String
        Get
            Return ResourceManager.GetString("ID_menu_logs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Production.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_Production() As String
        Get
            Return ResourceManager.GetString("ID_menu_Production", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to production.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_production1() As String
        Get
            Return ResourceManager.GetString("ID_menu_production1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Production order.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_productionOrder() As String
        Get
            Return ResourceManager.GetString("ID_menu_productionOrder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_System() As String
        Get
            Return ResourceManager.GetString("ID_menu_System", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SystemOption.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_SystemOption() As String
        Get
            Return ResourceManager.GetString("ID_menu_SystemOption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System Option.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_systemOption1() As String
        Get
            Return ResourceManager.GetString("ID_menu_systemOption1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to user management.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_userMgr() As String
        Get
            Return ResourceManager.GetString("ID_menu_userMgr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to user.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_users() As String
        Get
            Return ResourceManager.GetString("ID_menu_users", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;View.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_View() As String
        Get
            Return ResourceManager.GetString("ID_menu_View", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Command List &amp;Tree.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_ViewCmdTree() As String
        Get
            Return ResourceManager.GetString("ID_menu_ViewCmdTree", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Status &amp;Bar.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_ViewStatusbar() As String
        Get
            Return ResourceManager.GetString("ID_menu_ViewStatusbar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Window.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_Window() As String
        Get
            Return ResourceManager.GetString("ID_menu_Window", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Arrange Icons.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_WindowArrangeIcons() As String
        Get
            Return ResourceManager.GetString("ID_menu_WindowArrangeIcons", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cascade.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_WindowCascade() As String
        Get
            Return ResourceManager.GetString("ID_menu_WindowCascade", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tile &amp;Horizontal.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_WindowTileHorizontal() As String
        Get
            Return ResourceManager.GetString("ID_menu_WindowTileHorizontal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tile &amp;Vertical.
    '''</summary>
    Friend Shared ReadOnly Property ID_menu_WindowTileVertical() As String
        Get
            Return ResourceManager.GetString("ID_menu_WindowTileVertical", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to system.
    '''</summary>
    Friend Shared ReadOnly Property ID_mnu_System() As String
        Get
            Return ResourceManager.GetString("ID_mnu_System", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to user.
    '''</summary>
    Friend Shared ReadOnly Property ID_mnu_users() As String
        Get
            Return ResourceManager.GetString("ID_mnu_users", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please wait....
    '''</summary>
    Friend Shared ReadOnly Property ID_msg_Busy() As String
        Get
            Return ResourceManager.GetString("ID_msg_Busy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to delete this record?.
    '''</summary>
    Friend Shared ReadOnly Property ID_msg_ConfirmDeletion() As String
        Get
            Return ResourceManager.GetString("ID_msg_ConfirmDeletion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The application detected the following error:
    '''
    '''&quot;{0}&quot;
    ''' - {1}.
    '''</summary>
    Friend Shared ReadOnly Property ID_msg_CustomError() As String
        Get
            Return ResourceManager.GetString("ID_msg_CustomError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An Error has occurred In Module &quot;&quot;{0}&quot;&quot;.
    '''		
    '''Error Message: {1}
    '''Error Routine :{2}
    '''Error Source: {3}
    '''
    '''Please contact your system&apos;s administrator..
    '''</summary>
    Friend Shared ReadOnly Property ID_msg_Error() As String
        Get
            Return ResourceManager.GetString("ID_msg_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Record has been changed. Do you want To save it?.
    '''</summary>
    Friend Shared ReadOnly Property ID_msg_RecordChanged() As String
        Get
            Return ResourceManager.GetString("ID_msg_RecordChanged", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An Error occured on %1:\r\n%2.
    '''</summary>
    Friend Shared ReadOnly Property ID_msg_ValidError() As String
        Get
            Return ResourceManager.GetString("ID_msg_ValidError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settings.
    '''</summary>
    Friend Shared ReadOnly Property ID_reg_Setting() As String
        Get
            Return ResourceManager.GetString("ID_reg_Setting", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MainHeight.
    '''</summary>
    Friend Shared ReadOnly Property ID_reg_Setting_MainHeight() As String
        Get
            Return ResourceManager.GetString("ID_reg_Setting_MainHeight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MainLeft.
    '''</summary>
    Friend Shared ReadOnly Property ID_reg_Setting_MainLeft() As String
        Get
            Return ResourceManager.GetString("ID_reg_Setting_MainLeft", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MainTop.
    '''</summary>
    Friend Shared ReadOnly Property ID_reg_Setting_MainTop() As String
        Get
            Return ResourceManager.GetString("ID_reg_Setting_MainTop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MainWidth.
    '''</summary>
    Friend Shared ReadOnly Property ID_reg_Setting_MainWidth() As String
        Get
            Return ResourceManager.GetString("ID_reg_Setting_MainWidth", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add Row.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_AddRow() As String
        Get
            Return ResourceManager.GetString("ID_tb_AddRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Browse.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Browse() As String
        Get
            Return ResourceManager.GetString("ID_tb_Browse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancel.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Cancel() As String
        Get
            Return ResourceManager.GetString("ID_tb_Cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Close.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Close() As String
        Get
            Return ResourceManager.GetString("ID_tb_Close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CloseAll.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_CloseAll() As String
        Get
            Return ResourceManager.GetString("ID_tb_CloseAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Delete() As String
        Get
            Return ResourceManager.GetString("ID_tb_Delete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete Row.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_DelRow() As String
        Get
            Return ResourceManager.GetString("ID_tb_DelRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Edit() As String
        Get
            Return ResourceManager.GetString("ID_tb_Edit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit Row.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_EditRow() As String
        Get
            Return ResourceManager.GetString("ID_tb_EditRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Find.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_EXEFind() As String
        Get
            Return ResourceManager.GetString("ID_tb_EXEFind", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to First.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_First() As String
        Get
            Return ResourceManager.GetString("ID_tb_First", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Form.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Form() As String
        Get
            Return ResourceManager.GetString("ID_tb_Form", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Last.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Last() As String
        Get
            Return ResourceManager.GetString("ID_tb_Last", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Main.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Main() As String
        Get
            Return ResourceManager.GetString("ID_tb_Main", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_New() As String
        Get
            Return ResourceManager.GetString("ID_tb_New", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Next.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Next() As String
        Get
            Return ResourceManager.GetString("ID_tb_Next", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Open.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Open() As String
        Get
            Return ResourceManager.GetString("ID_tb_Open", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Previous.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Previous() As String
        Get
            Return ResourceManager.GetString("ID_tb_Previous", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Print.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Print() As String
        Get
            Return ResourceManager.GetString("ID_tb_Print", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quit the application.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Quit() As String
        Get
            Return ResourceManager.GetString("ID_tb_Quit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Refresh.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Refresh() As String
        Get
            Return ResourceManager.GetString("ID_tb_Refresh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Save.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Save() As String
        Get
            Return ResourceManager.GetString("ID_tb_Save", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search.
    '''</summary>
    Friend Shared ReadOnly Property ID_tb_Search() As String
        Get
            Return ResourceManager.GetString("ID_tb_Search", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add a row item.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_AddRow() As String
        Get
            Return ResourceManager.GetString("ID_tbt_AddRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter Browse Mode.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Browse() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Browse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancel changes.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Cancel() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Close.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Close() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Close All.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_CloseAll() As String
        Get
            Return ResourceManager.GetString("ID_tbt_CloseAll", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete a record.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Delete() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Delete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete a row item.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_DelRow() As String
        Get
            Return ResourceManager.GetString("ID_tbt_DelRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter Edit Mode.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Edit() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Edit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit a row item.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_EditRow() As String
        Get
            Return ResourceManager.GetString("ID_tbt_EditRow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Execute Search.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_EXEFind() As String
        Get
            Return ResourceManager.GetString("ID_tbt_EXEFind", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Go to the first record.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_First() As String
        Get
            Return ResourceManager.GetString("ID_tbt_First", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Show In a Form View.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Form() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Form", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Go to the last record.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Last() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Last", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Show switchboard.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Main() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Main", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Create new record.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_New() As String
        Get
            Return ResourceManager.GetString("ID_tbt_New", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Go to the next record.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Next() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Next", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Open.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Open() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Open", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Go to the previous record.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Previous() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Previous", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Print.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Print() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Print", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quit the application.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Quit() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Quit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Refresh records.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Refresh() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Refresh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Save a record.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Save() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Save", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter Search Mode.
    '''</summary>
    Friend Shared ReadOnly Property ID_tbt_Search() As String
        Get
            Return ResourceManager.GetString("ID_tbt_Search", resourceCulture)
        End Get
    End Property
End Class
