'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行库版本:2.0.50727.1433
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.1433 版自动生成。
'
Namespace RFWebService
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.33.128/RF/RFWebService.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_svr_datetime", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function get_svr_datetime() As String
            Dim results() As Object = Me.Invoke("get_svr_datetime", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Beginget_svr_datetime(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("get_svr_datetime", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endget_svr_datetime(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTxt_ModifyTime", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getTxt_ModifyTime() As String
            Dim results() As Object = Me.Invoke("getTxt_ModifyTime", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegingetTxt_ModifyTime(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getTxt_ModifyTime", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetTxt_ModifyTime(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownLoadSingleFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DownLoadSingleFile(ByVal as_sn As String, ByVal as_FileName As String, ByRef as_serr As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("DownLoadSingleFile", New Object() {as_sn, as_FileName, as_serr})
            as_serr = CType(results(1),String)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Function BeginDownLoadSingleFile(ByVal as_sn As String, ByVal as_FileName As String, ByVal as_serr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DownLoadSingleFile", New Object() {as_sn, as_FileName, as_serr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndDownLoadSingleFile(ByVal asyncResult As System.IAsyncResult, ByRef as_serr As String) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_serr = CType(results(1),String)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownLoadFileLot", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DownLoadFileLot(ByVal as_sn As String, ByVal as_fileName As String, ByVal al_off As Long, ByVal al_len As Long, ByRef as_sErr As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("DownLoadFileLot", New Object() {as_sn, as_fileName, al_off, al_len, as_sErr})
            as_sErr = CType(results(1),String)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Function BeginDownLoadFileLot(ByVal as_sn As String, ByVal as_fileName As String, ByVal al_off As Long, ByVal al_len As Long, ByVal as_sErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DownLoadFileLot", New Object() {as_sn, as_fileName, al_off, al_len, as_sErr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndDownLoadFileLot(ByVal asyncResult As System.IAsyncResult, ByRef as_sErr As String) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_sErr = CType(results(1),String)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpLoadSingleFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpLoadSingleFile(ByVal as_sn As String, ByVal as_FileName As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal FileData() As Byte, ByRef as_serr As String) As String
            Dim results() As Object = Me.Invoke("UpLoadSingleFile", New Object() {as_sn, as_FileName, FileData, as_serr})
            as_serr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginUpLoadSingleFile(ByVal as_sn As String, ByVal as_FileName As String, ByVal FileData() As Byte, ByVal as_serr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpLoadSingleFile", New Object() {as_sn, as_FileName, FileData, as_serr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndUpLoadSingleFile(ByVal asyncResult As System.IAsyncResult, ByRef as_serr As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_serr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteSQL_DS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecuteSQL_DS(ByVal as_sn As String, ByVal as_sql As String, ByRef as_sErr As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ExecuteSQL_DS", New Object() {as_sn, as_sql, as_sErr})
            as_sErr = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginExecuteSQL_DS(ByVal as_sn As String, ByVal as_sql As String, ByVal as_sErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ExecuteSQL_DS", New Object() {as_sn, as_sql, as_sErr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndExecuteSQL_DS(ByVal asyncResult As System.IAsyncResult, ByRef as_sErr As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_sErr = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteSQL_CNT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecuteSQL_CNT(ByVal as_sn As String, ByVal as_sql As String, ByRef as_sErr As String) As String
            Dim results() As Object = Me.Invoke("ExecuteSQL_CNT", New Object() {as_sn, as_sql, as_sErr})
            as_sErr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginExecuteSQL_CNT(ByVal as_sn As String, ByVal as_sql As String, ByVal as_sErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ExecuteSQL_CNT", New Object() {as_sn, as_sql, as_sErr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndExecuteSQL_CNT(ByVal asyncResult As System.IAsyncResult, ByRef as_sErr As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_sErr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteScalar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ExecuteScalar(ByVal as_sn As String, ByVal as_sql As String, ByRef as_sErr As String) As String
            Dim results() As Object = Me.Invoke("ExecuteScalar", New Object() {as_sn, as_sql, as_sErr})
            as_sErr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginExecuteScalar(ByVal as_sn As String, ByVal as_sql As String, ByVal as_sErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ExecuteScalar", New Object() {as_sn, as_sql, as_sErr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndExecuteScalar(ByVal asyncResult As System.IAsyncResult, ByRef as_sErr As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_sErr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunProcedure_Str", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunProcedure_Str(ByVal as_sn As String, ByVal as_proName As String, ByVal as_Params As String, ByRef sErr As String) As String
            Dim results() As Object = Me.Invoke("RunProcedure_Str", New Object() {as_sn, as_proName, as_Params, sErr})
            sErr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginRunProcedure_Str(ByVal as_sn As String, ByVal as_proName As String, ByVal as_Params As String, ByVal sErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RunProcedure_Str", New Object() {as_sn, as_proName, as_Params, sErr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRunProcedure_Str(ByVal asyncResult As System.IAsyncResult, ByRef sErr As String) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            sErr = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunProcedure_DS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RunProcedure_DS(ByVal as_sn As String, ByVal as_proName As String, ByVal as_Params As String, ByRef as_sErr As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RunProcedure_DS", New Object() {as_sn, as_proName, as_Params, as_sErr})
            as_sErr = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginRunProcedure_DS(ByVal as_sn As String, ByVal as_proName As String, ByVal as_Params As String, ByVal as_sErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RunProcedure_DS", New Object() {as_sn, as_proName, as_Params, as_sErr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndRunProcedure_DS(ByVal asyncResult As System.IAsyncResult, ByRef as_sErr As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_sErr = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wf_sp_hht_getTaskList", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function wf_sp_hht_getTaskList(ByVal as_sn As String, ByVal as_sku_no As String, ByVal as_assigned_opt As String, ByRef as_sErr As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("wf_sp_hht_getTaskList", New Object() {as_sn, as_sku_no, as_assigned_opt, as_sErr})
            as_sErr = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function Beginwf_sp_hht_getTaskList(ByVal as_sn As String, ByVal as_sku_no As String, ByVal as_assigned_opt As String, ByVal as_sErr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("wf_sp_hht_getTaskList", New Object() {as_sn, as_sku_no, as_assigned_opt, as_sErr}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endwf_sp_hht_getTaskList(ByVal asyncResult As System.IAsyncResult, ByRef as_sErr As String) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            as_sErr = CType(results(1),String)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
